// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVy8jTIv94olpDIdJuLCpLFlUKb2MeOU',
    appId: '1:232278809894:web:7e3a71df2ae7cc46bff5e7',
    messagingSenderId: '232278809894',
    projectId: 'hostel-manager-2d6ff',
    authDomain: 'hostel-manager-2d6ff.firebaseapp.com',
    databaseURL: 'https://hostel-manager-2d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'hostel-manager-2d6ff.firebasestorage.app',
    measurementId: 'G-QP0LFTFJQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXO88dlSgxt0oOUMYRZ55IZMJtRJyH_7Y',
    appId: '1:232278809894:android:3d0e5b388f6f659ebff5e7',
    messagingSenderId: '232278809894',
    projectId: 'hostel-manager-2d6ff',
    databaseURL: 'https://hostel-manager-2d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'hostel-manager-2d6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPLuTHFspYg08EsL3FYOjCuQEItEgBFU',
    appId: '1:232278809894:ios:5b415e1ee637c5abbff5e7',
    messagingSenderId: '232278809894',
    projectId: 'hostel-manager-2d6ff',
    databaseURL: 'https://hostel-manager-2d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'hostel-manager-2d6ff.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSPLuTHFspYg08EsL3FYOjCuQEItEgBFU',
    appId: '1:232278809894:ios:5b415e1ee637c5abbff5e7',
    messagingSenderId: '232278809894',
    projectId: 'hostel-manager-2d6ff',
    databaseURL: 'https://hostel-manager-2d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'hostel-manager-2d6ff.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoVy8jTIv94olpDIdJuLCpLFlUKb2MeOU',
    appId: '1:232278809894:web:1f0a6a815ae94099bff5e7',
    messagingSenderId: '232278809894',
    projectId: 'hostel-manager-2d6ff',
    authDomain: 'hostel-manager-2d6ff.firebaseapp.com',
    databaseURL: 'https://hostel-manager-2d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'hostel-manager-2d6ff.firebasestorage.app',
    measurementId: 'G-8DQG0L3MR7',
  );
}
